# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5dc6b35b00160d13a96cf31b31611fe878878ca2bc21e38480495cfaa2066a28f3798208f06c4218e8fa1c0f0274fb2a14e1a83a2832adcdb216598ae5bf55c

test:
  secret_key_base: dc05991576f79ee78c7dc609d3b4344c21ebb4cf13227b3c210523df36ea4c4473e9215ba3b6642adbb277c5ab6726f86e349ec50d12941238fa5f66849f797f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
